front_homepage:
    path:     /
    defaults: { _controller: FrontBundle:Default:index }

front_commandes:
    resource: "@FrontBundle/Resources/config/routing/commandes.yml"
    prefix:   /commandes
front_evennements:
    resource: "@FrontBundle/Resources/config/routing/evennements.yml"
    prefix:   /evennements
