front_homepage:
    path:     /
    defaults: { _controller: FrontBundle:Default:index }

front_commandes:
    resource: "@FrontBundle/Resources/config/routing/commandes.yml"
    prefix:   /commandes

front_abonnemnts:
    resource: "@FrontBundle/Resources/config/routing/ComAbonnements.yml"
    prefix:   /abonnements