front_homepage:
    path:     /
    defaults: { _controller: FrontBundle:Default:index }

<<<<<<< HEAD
front_reclamations:
    resource: "@FrontBundle/Resources/config/routing/reclamations.yml"
    prefix:   /reclamations
=======
front_commandes:
    resource: "@FrontBundle/Resources/config/routing/commandes.yml"
    prefix:   /commandes
>>>>>>> be044d964401d0bba5c51632b5d29d82fb7c44ee
