front_homepage:
    path:     /
    defaults: { _controller: FrontBundle:Default:index }
front_reservation:
    resource: "@FrontBundle/Resources/config/routing/reservation.yml"
    prefix:   /reservations

api_souk:
    resource: "@FrontBundle/Resources/config/routing/api.yml"
    prefix:   /mobile

front_reclamations:
    resource: "@FrontBundle/Resources/config/routing/reclamations.yml"
    prefix:   /reclamations
front_commandes:
    resource: "@FrontBundle/Resources/config/routing/commandes.yml"
    prefix:   /commandes

front_abonnemnts:
    resource: "@FrontBundle/Resources/config/routing/ComAbonnements.yml"
    prefix:   /abonnements

front_evennements:
    resource: "@FrontBundle/Resources/config/routing/evennements.yml"
    prefix:   /evennements

commercial_annonces:
    resource: "@FrontBundle/Resources/config/routing/annoncesCommercial.yml"
    prefix:   /

client_annonces:
    resource: "@FrontBundle/Resources/config/routing/annonces.yml"
    prefix:   /annonces

