front_homepage:
    path:     /
    defaults: { _controller: FrontBundle:Default:index }

front_reclamations:
    resource: "@FrontBundle/Resources/config/routing/reclamations.yml"
    prefix:   /reclamations
front_commandes:
    resource: "@FrontBundle/Resources/config/routing/commandes.yml"
    prefix:   /commandes

front_abonnemnts:
    resource: "@FrontBundle/Resources/config/routing/ComAbonnements.yml"
    prefix:   /abonnements
<<<<<<< HEAD

=======
>>>>>>> 9e17d445cd6cc8e144fc827de2ff6f35022452c9
front_evennements:
    resource: "@FrontBundle/Resources/config/routing/evennements.yml"
    prefix:   /evennements
