front_homepage:
    path:     /
    defaults: { _controller: FrontBundle:Default:index }

front_reclamations:
    resource: "@FrontBundle/Resources/config/routing/reclamations.yml"
    prefix:   /reclamations