api_homepage:
    path:     /
    defaults: { _controller: ApiBundle:Default:index }
#web service connexion
get_User:
    path:     /user/{login}/{password}
    defaults: { _controller: ApiBundle:UserApi:getUser}
#nour service
api_commandes:
    resource: "@ApiBundle/Resources/config/routing/commandes.yml"
    prefix:   /commandes
#web service Haifa Daoud
api_annonces:
    resource: "@ApiBundle/Resources/config/routing/annonces.yml"
    prefix:   /annonces

api_image:
    path: /getImageByIdAnnonce/{id}
    defaults: { _controller: ApiBundle:ImageApi:GetImageById}

api_liste_categorie:
    path: /categorie/all
    defaults: { _controller: ApiBundle:CategorieApi:lstCategorie}

#service Soumaya
api_reclamations:
    resource: "@ApiBundle/Resources/config/routing/reclamations.yml"
    prefix:   /reclamations
#service Safa
api_commentaireAnc:
    resource: "@ApiBundle/Resources/config/routing/commentaireAnc.yml"
    prefix:   /commentaire

#service salsabil
api_evenements:
    resource: "@ApiBundle/Resources/config/routing/evenements.yml"
    prefix:   /evenements

