api_homepage:
    path:     /
    defaults: { _controller: ApiBundle:Default:index }
#web service connexion
get_User:
    path:     /user/{login}/{password}
    defaults: { _controller: ApiBundle:UserApi:getUser}
#web service Nour Banbia
liste_commandes:
    path:     /commandes/liste/{id}
    defaults: { _controller: ApiBundle:CommandesApi:liste }

create_commande:
    path:     /commandes/new/{annonce}/{date}/{quantite}/{client}
    defaults: { _controller: ApiBundle:CommandesApi:create }
#web service Haifa Daoud
get_All_Annonces:
    path:     /allAnnonces
    defaults: { _controller: ApiBundle:AnnoncesApi:getAllAnnonces}
