api_homepage:
    path:     /
    defaults: { _controller: ApiBundle:Default:index }
#web service connexion
get_User:
    path:     /user/{login}/{password}
    defaults: { _controller: ApiBundle:UserApi:getUser}
#nour service
api_commandes:
    resource: "@ApiBundle/Resources/config/routing/commandes.yml"
    prefix:   /commandes
#web service Haifa Daoud
api_annonces:
    resource: "@ApiBundle/Resources/config/routing/annonces.yml"
    prefix:   /annonces
#service Soumaya
api_reclamations:
    resource: "@ApiBundle/Resources/config/routing/reclamations.yml"
    prefix:   /reclamations
#Service SafaBenBarka
api_abonnements:
    resource: "@ApiBundle/Resources/config/routing/abonnements.yml"
    prefix:   /abonnements
#service Safa
api_commentaireAnc:
    resource: "@ApiBundle/Resources/config/routing/commentaireAnc.yml"
    prefix:   /commentaire
api_commentaireEvs:
    resource: "@ApiBundle/Resources/config/routing/commentaireEvs.yml"
    prefix:   /commentaire
#service salsabil
api_evenements:
    resource: "@ApiBundle/Resources/config/routing/evenements.yml"
    prefix:   /evenements
