api_homepage:
    path:     /
    defaults: { _controller: ApiBundle:Default:index }
#web service connexion
get_User:
    path:     /user/{login}/{password}
    defaults: { _controller: ApiBundle:UserApi:getUser}
#nour service
api_commandes:
    resource: "@ApiBundle/Resources/config/routing/commandes.yml"
    prefix:   /commandes
#web service Haifa Daoud
get_All_Annonces:
    path:     /allAnnonces
    defaults: { _controller: ApiBundle:AnnoncesApi:getAllAnnonces}

#service Soumaya
#api_reclamations:
     #resource: "@ApiBundle/Resources/config/routing/reclamtion.yml"
     #prefix:   /reclamation.yml
liste_reclamations:
    path:     /reclamations/liste/{id}
    defaults: { _controller: ApiBundle:ReclamationApi:listeRec }
