<?php

namespace Souk\BackBundle\Repository;

/**
 * AnnoncesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnoncesRepository extends \Doctrine\ORM\EntityRepository
{
    public function signales()
    {
        return $this->createQueryBuilder('p')
            // p.category refers to the "category" property on product
            ->innerJoin('p.signals', 's')
            // selects all the category data to avoid the query
            ->addSelect('s')
            ->andWhere('s.annonce = p.id')
            ->getQuery()
            ->getResult();
    }
  public function findByName($libelle)
  {
    $sql = 'SELECT a FROM Souk\BackBundle\Entity\Annonces   a where a.titre like :libelle and a.disponible = :disponible ORDER BY a.dateCreation DESC';
    $query = $this->getEntityManager()->createQuery($sql)->setParameter('titre', '%'.$libelle.'%')->setParameter('disponible', 1);

    return $query->execute();
  }
  public function findAllOrderedByDate()
  {
    $sql = 'SELECT a FROM Souk\BackBundle\Entity\Annonces  a where a.disponible = :disponible ORDER BY a.dateCreation DESC';
    $query = $this->getEntityManager()->createQuery($sql)->setParameter('disponible', 1);

    return $query->execute();
  }
  public function findAllOrderedByDateCommercial($user)
  {
    $sql = 'SELECT a FROM Souk\BackBundle\Entity\Annonces  a where a.commercial = :commercial ORDER BY a.dateCreation DESC';
    $query = $this->getEntityManager()->createQuery($sql)->setParameter('commercial', $user);

    return $query->execute();
  }
}
