<?php

namespace Souk\BackBundle\Repository;

/**
 * AnnoncesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnoncesRepository extends \Doctrine\ORM\EntityRepository
{
    public function signales()
    {
        return $this->createQueryBuilder('p')
            // p.category refers to the "category" property on product
            ->innerJoin('p.signals', 's')
            // selects all the category data to avoid the query
            ->addSelect('s')
            ->andWhere('s.annonce = p.id')
            ->getQuery()
            ->getResult();
    }
}
