<?php

namespace Souk\BackBundle\Repository;

/**
 * HistoriqueAbsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoriqueAbsRepository extends \Doctrine\ORM\EntityRepository
{
  public function findAbonnementByIdUserDate($id,$dateJour)
  {
    $sql = 'SELECT h FROM Souk\BackBundle\Entity\HistoriqueAbs   h where h.commercial =:id  and h.dateAb >=:dateJour ';
    $query = $this->getEntityManager()->createQuery($sql)->setParameter('id',$id)->setParameter('dateJour', $dateJour->format('Y-m-d'));

    return $query->execute();

  }
}