categories_index:
    path:     /
    defaults: { _controller: "BackBundle:Categories:index" }
    methods:  GET

categories_new:
    path:     /new
    defaults: { _controller: "BackBundle:Categories:new" }
    methods:  [GET, POST]

categories_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackBundle:Categories:edit" }
    methods:  [GET, POST]

categories_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackBundle:Categories:delete" }
    methods:  [GET, POST]
