back_evennements:
    resource: "@BackBundle/Resources/config/routing/evennements.yml"
    prefix:   /evennements



back_homepage:
    path:     /
    defaults: { _controller: BackBundle:Default:index }
