client_annonces_index:
    path:     /
    defaults: { _controller: FrontBundle:Annonces:index }
    methods:  GET
annonces_index_by_categories:
    path:    /categorie/{categorie}
    defaults: { _controller: FrontBundle:Annonces:listerbyCategorie }
annonces_index_by_categoriesDefault:
    path:    annonce/categorie/{categorie}
    defaults: { _controller: FrontBundle:Default:listeruserbyCategorie }
annonces_show:
    path:     /{id}/show
    defaults: { _controller: FrontBundle:Annonces:show }
    methods:  [GET, POST]

commentairesAnc_new:
    path:     /annonce/{annonce}
    defaults: { _controller: FrontBundle:Annonces:new}
commentairesAnc_delete:
    path:     /delete_com/{com}/{annonce}
    defaults: { _controller: FrontBundle:Annonces:deleteComAnc}
commentairesAnc_edit:
    path:     /edit_com/{com}/{annonce}
    defaults: { _controller: FrontBundle:Annonces:edit}
