client_annonces_index:
    path:     /
    defaults: { _controller: FrontBundle:Annonces:index }
    methods:  GET
annonces_index_by_categorie:
    path:    /{categorie}
    defaults: { categorie_controller: FrontBundle:Annonces:indexbyCategorie }
    methods:  GET
annonces_show:
    path:     /{id}/show
    defaults: { _controller: FrontBundle:Annonces:show }
    methods:  [GET, POST]

commentairesAnc_new:
    path:     /annonce/{annonce}
    defaults: { _controller: FrontBundle:Annonces:new}
commentairesAnc_delete:
    path:     /delete_com/{com}/{annonce}
    defaults: { _controller: FrontBundle:Annonces:deleteComAnc}
commentairesAnc_edit:
    path:     /edit_com/{com}/{annonce}
    defaults: { _controller: FrontBundle:Annonces:edit}
all:
    path:     /commentaire/all
    defaults: { _controller: FrontBundle:Annonces:all}
find_commentaire:
    path:     /commentaire/find/{id}
    defaults: { _controller: FrontBundle:Annonces:find}
create_commentaire:
    path:     /commentaire/new_Anc/{annonce}
    defaults: { _controller: FrontBundle:Annonces:newAnc}