abonnements_com_new:
    path:     /new
    defaults: { _controller: "FrontBundle:ComAbonnements:new" }
    methods:  GET

abonnements_com_show:
    path:     /show/{id}
    defaults: { _controller: "FrontBundle:ComAbonnements:show" }
    methods:  GET

abonnements_com_index:
    path:     /
    defaults: { _controller: "FrontBundle:ComAbonnements:index" }
    methods:  GET