commentairesEvs_new:
    path:     /evennement/{evennement}
    defaults: { _controller: FrontBundle:CommentaireEvs:new}

commentairesEvs_delete:
    path:     /delete_com_Evs/{evennement}/{com}
    defaults: { _controller: FrontBundle:CommentaireEvs:delete}
commentairesEvs_Edit:
    path:     /edit_com_Evs/{com}/{evennement}
    defaults: { _controller: FrontBundle:CommentaireEvs:edit}
all:
    path:     /commentaire/all
    defaults: { _controller: FrontBundle:CommentaireEvs:all}
find_commentaire:
    path:     /commentaire/find/{id}
    defaults: { _controller: FrontBundle:CommentaireEvs:find}
create_commentaire:
    path:     /commentaire/new_Anc/{evennement}
    defaults: { _controller: FrontBundle:CommentaireEvs:newEvs}


