commentairesEvs_new:
    path:     /evennement/{evennement}
    defaults: { _controller: FrontBundle:CommentaireEvs:new}

commentairesEvs_delete:
    path:     /delete_com_Evs/{id_Evs}
    defaults: { _controller: FrontBundle:CommentaireEvs:delete}

