commandes_index:
    path:     /
    defaults: { _controller: "FrontBundle:Commandes:index" }
    methods:  GET

commandes_show:
    path:     /{id}/show
    defaults: { _controller: "FrontBundle:Commandes:show" }
    methods:  GET

commandes_new:
    path:     /new/{annonce}
    defaults: { _controller: "FrontBundle:Commandes:new" }
    methods:  [GET, POST]

commandes_edit:
    path:     /{id}/edit
    defaults: { _controller: "FrontBundle:Commandes:edit" }
    methods:  [GET, POST]

commandes_modif:
    path:     /modif
    defaults: { _controller: "FrontBundle:Commandes:modifier" }
    methods:  [GET, POST]
commandes_valid:
    path:     /{id}/valid
    defaults: { _controller: "FrontBundle:Commandes:valid" }
    methods:  [GET, POST]

commandes_delete:
    path:     /{id}/delete
    defaults: { _controller: "FrontBundle:Commandes:delete" }
    methods:  DELETE
#web service
liste_commandes:
    path:     /liste/{id}
    defaults: { _controller: "FrontBundle:Commandes:liste" }

create_commande:
    path:     /{annonce}/{date}/{quantite}/{client}
    defaults: { _controller: "FrontBundle:Commandes:create" }


