api_Annonces:
    path:     /all
    defaults: { _controller: ApiBundle:AnnoncesApi:getAllAnnonces}
get_Annonce:
    path:     /AnnoncesById/{id}
    defaults: { _controller: ApiBundle:AnnoncesApi:GetAnnonceById}
ajouter_Annonce:
     path:     /ajouter/{commercial}/{prix}/{categorie}/{description}/{titre}
     defaults: { _controller: ApiBundle:AnnoncesApi:create}
modifier_Annonce:
     path:     /modifier/{idannonces}/{prix}/{categorie}/{description}/{titre}
     defaults: { _controller: ApiBundle:AnnoncesApi:modifier}
supprimer_Annonce:
      path:     /supprimer/{id}
      defaults: { _controller: ApiBundle:AnnoncesApi:supprimer}