get_All_Annonces:
    path:     /allAnnonces
    defaults: { _controller: ApiBundle:AnnoncesApi:getAllAnnonces}
get_Annonce:
    path:     /AnnoncesById/{id}
    defaults: { _controller: ApiBundle:AnnoncesApi:GetAnnonceById}
