#web service Nour Banbia
liste_commandes:
    path:     /commandes/liste/{id}
    defaults: { _controller: ApiBundle:CommandesApi:liste }

create_commande:
    path:     /commandes/new/{annonce}/{date}/{quantite}/{client}
    defaults: { _controller: ApiBundle:CommandesApi:create }