get_All_Evenements:
    path:     /allEvents
    defaults: { _controller: ApiBundle:EvenementsApi:getEvents}
get_All_Evenements_by_user:
    path:     /allEvents/user/{id}
    defaults: { _controller: ApiBundle:EvenementsApi:getEventsbyUser}

get_All_Evenements_by_id:
    path:     /allEvents/{id}
    defaults: { _controller: ApiBundle:EvenementsApi:getEventsbyId}

create_commande:
    path:     /new/{commercial}/{titre}/{prix}/{lieu}
    defaults: { _controller: ApiBundle:EvenementsApi:create }